import pytest


@pytest.mark.asyncio
async def test_get_weather(async_client):
    """Корректность результата на валидные данные
    (в том числе и НЕвалидные координаты)"""
    test_cases = [
        (40.7128, -74.0060),  # Нью-Йорк, США
        (4.7110, -74.0721),  # Богота, Колумбия
        (-23.5505, -46.6333),  # Сан-Паулу, Бразилия
        (55.7558, 37.6173),  # Москва, Россия
        (48.8566, 2.3522),  # Париж, Франция
        (31.2357, 30.0444),  # Александрия, Египет
        (-33.8688, 151.2093),  # Сидней, Австралия
        (64.1265, -21.8174),  # Рейкьявик, Исландия (полярный круг)
        (78.2232, 15.6267)  # Лонгйир, Шпицберген (Арктика)
    ]

    for (lat, lon) in test_cases:
        response = await async_client.get(
            "/get-weather",
            params={"latitude": lat, "longitude": lon}
        )

        assert response.status_code == 200, (
            f"Ошибка для координат: ({lat}, {lon}); "
            f"статус: {response.status_code}"
        )
